// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRrxAiWXzXUF-Xt04Vdx9JKDgzWeQLq2Q',
    appId: '1:203373570079:web:c046f01e8caae15df48d2a',
    messagingSenderId: '203373570079',
    projectId: 'aplicativo-turismo-flutter',
    authDomain: 'aplicativo-turismo-flutter.firebaseapp.com',
    storageBucket: 'aplicativo-turismo-flutter.appspot.com',
    measurementId: 'G-KD3R6ECKXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLjtUICvIKcFH9yFY6gkoFusMWR8XGvjU',
    appId: '1:203373570079:android:83ed1b635a877618f48d2a',
    messagingSenderId: '203373570079',
    projectId: 'aplicativo-turismo-flutter',
    storageBucket: 'aplicativo-turismo-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm-djFBrvsus9MDNTPfV4rD1i-fFhTV34',
    appId: '1:203373570079:ios:1f67108742a2fc86f48d2a',
    messagingSenderId: '203373570079',
    projectId: 'aplicativo-turismo-flutter',
    storageBucket: 'aplicativo-turismo-flutter.appspot.com',
    iosClientId: '203373570079-d6k53c0la0clnllnn8c4v7umkas37q9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplicativoTurismo',
  );
}
